// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// derep_map_only
void derep_map_only(Rcpp::List derep);
RcppExport SEXP _optimotu_pipeline_derep_map_only(SEXP derepSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type derep(derepSEXP);
    derep_map_only(derep);
    return R_NilValue;
END_RCPP
}
// fastq_names
Rcpp::CharacterVector fastq_names(std::string x);
RcppExport SEXP _optimotu_pipeline_fastq_names(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fastq_names(x));
    return rcpp_result_gen;
END_RCPP
}
// fastq_stage_map
Rcpp::DataFrame fastq_stage_map(std::string raw, std::vector<std::string> stages);
RcppExport SEXP _optimotu_pipeline_fastq_stage_map(SEXP rawSEXP, SEXP stagesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type raw(rawSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type stages(stagesSEXP);
    rcpp_result_gen = Rcpp::wrap(fastq_stage_map(raw, stages));
    return rcpp_result_gen;
END_RCPP
}
// fastq_stage_map2
Rcpp::DataFrame fastq_stage_map2(std::string raw, std::string stage1, std::string stage2);
RcppExport SEXP _optimotu_pipeline_fastq_stage_map2(SEXP rawSEXP, SEXP stage1SEXP, SEXP stage2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type raw(rawSEXP);
    Rcpp::traits::input_parameter< std::string >::type stage1(stage1SEXP);
    Rcpp::traits::input_parameter< std::string >::type stage2(stage2SEXP);
    rcpp_result_gen = Rcpp::wrap(fastq_stage_map2(raw, stage1, stage2));
    return rcpp_result_gen;
END_RCPP
}
// fastq_qual_bins
Rcpp::IntegerVector fastq_qual_bins(std::vector<std::string> fastq, int max_n, int offset);
RcppExport SEXP _optimotu_pipeline_fastq_qual_bins(SEXP fastqSEXP, SEXP max_nSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type fastq(fastqSEXP);
    Rcpp::traits::input_parameter< int >::type max_n(max_nSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(fastq_qual_bins(fastq, max_n, offset));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_optimotu_pipeline_derep_map_only", (DL_FUNC) &_optimotu_pipeline_derep_map_only, 1},
    {"_optimotu_pipeline_fastq_names", (DL_FUNC) &_optimotu_pipeline_fastq_names, 1},
    {"_optimotu_pipeline_fastq_stage_map", (DL_FUNC) &_optimotu_pipeline_fastq_stage_map, 2},
    {"_optimotu_pipeline_fastq_stage_map2", (DL_FUNC) &_optimotu_pipeline_fastq_stage_map2, 3},
    {"_optimotu_pipeline_fastq_qual_bins", (DL_FUNC) &_optimotu_pipeline_fastq_qual_bins, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_optimotu_pipeline(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
