#' Detect Nuclear Mitochondrial Paralogs (NUMTs)
#' @param a2m (`character`) name of an A2M file containing a multiple sequence
#' alignment as generated by `hmmalign()`.  In particular, insertions relative
#' to the reference alignment should be present as masked (lower-case)
#' characters.
#' @param id_is_int (`logical`) if `TRUE`, return the sequence index as an
#' integer
#' @return `data.frame` with columns `seq_id` (or `seq_idx` if `id_is_int` is
#' `TRUE`), `numt_indicator`, `pos`, and `len`, where `numt_indicator` is one of
#' "frameshift" or "stop_codon", `pos` is the 1-based position of the indicator,
#' and `len` is the length of the indicator.
#' @export
detect_numts <- function(a2m, id_is_int = FALSE) {
  # avoid R CMD check NOTE: no visible binding for global variable
  pos <- len <- i <- seq_id <- numt_indicator <- NULL

  checkmate::assert_file(a2m, access = "r")
  checkmate::assert_flag(id_is_int)
  a2m <- Biostrings::readBStringSet(a2m) |>
    sub(pattern = "^[acgt]+", replacement = "") |>
    sub(pattern = "[acgt]+$", replacement = "")

  a2m_frameshifts <- gregexpr("-+|[actg]+", a2m) |>
    purrr::map_dfr(
      ~data.frame(pos = .x, len = attr(.x, "match.length")),
      .id = "i"
    ) |>
    dplyr::filter(pos != 1L, pos + len != 659L, len %% 3 != 0)
  a2m_stops <- gregexpr("TA[GA]", a2m) |>
    purrr::map_dfr(
      ~data.frame(pos = .x, len = attr(.x, "match.length")),
      .id = "i"
    ) |>
    dplyr::filter(pos %% 3 == 2, pos > 0)
  numts = dplyr::bind_rows(
    frameshift = a2m_frameshifts,
    stop_codon = a2m_stops,
    .id = "numt_indicator"
  ) |>
    dplyr::mutate(seq_id = names(a2m)[as.integer(i)], .keep = "unused")

  if (id_is_int) {
    dplyr::transmute(
      numts,
      seq_idx = as.integer(seq_id),
      numt_indicator,
      pos,
      len
    )
  } else (
    dplyr::select(numts, seq_id, numt_indicator, pos, len)
  )
}
