# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

derep_map_only <- function(derep) {
    invisible(.Call(`_optimotu_pipeline_derep_map_only`, derep))
}

fastq_names <- function(x) {
    .Call(`_optimotu_pipeline_fastq_names`, x)
}

fastq_stage_map <- function(raw, stages) {
    .Call(`_optimotu_pipeline_fastq_stage_map`, raw, stages)
}

fastq_stage_map2 <- function(raw, stage1, stage2) {
    .Call(`_optimotu_pipeline_fastq_stage_map2`, raw, stage1, stage2)
}

fastq_qual_bins <- function(fastq, max_n = 1e9L, offset = 33L) {
    .Call(`_optimotu_pipeline_fastq_qual_bins`, fastq, max_n, offset)
}

